### ISSUE TITLE
Support for TypeScript?

### ISSUE THREAD

**Issue by maacpiash** [nano-react-app/nano-react-app#11]

**Comment by adrianmcli** [comment]
PRs welcome. Would be a good idea to have it as a flagged option.

**Comment by mgreasly** [comment]
Happy to make changes for a PR for this. Sounds like there are 2 parts to it:

* Update this repo to include a flag on the cmd, maybe
```
npx nano-react-app my-app --t tsx
```

* create a new template repo that uses tsx and has the tsconfig etc required for typescript support

If that sounds reasonable, I can provide the template project if you want to host here and then make the updates to include the flag.

**Comment by adrianmcli** [comment]
@mgreasly Yep, I'll be happy to merge those 2 changes if you are happy to provide the PR!

**Comment by mgreasly** [comment]
For the *new* typescript template, do you want to create a new repo to host it? Happy to create one, but it probably makes more sense for you too and to 'own' it.

**Comment by mgreasly** [comment]
Hey, I've created a repo for the typescript template at https://github.com/mgreasly/nano-react-app-typescript-template.

**Comment by mgreasly** [comment]
@adrianmcli raised PR with updates to this project to allow different template projects and a flag to use a TSX project.
```
nano-create-app [name] --tsx
```
I've used a URL to a template project assuming you'll host the template for the typescript project. I thought that made more sense than having it somewhere random.

**Comment by adrianmcli** [comment]
@mgreasly I've just left my job so I'm going to spend a lot more time on this project. So I've actually created an organization: https://github.com/nano-react-app

If you want to transfer your template project over to the organization, I'd be happy to work with you together on it.

**Comment by adrianmcli** [comment]
Typescript support is now available! Just run it with a `--ts` flag:

```
npx nano-react-app my-app --ts
```

**Comment by adrianmcli** [comment]
Actually we're still waiting on this issue in Parcel to get resolved: https://github.com/parcel-bundler/parcel/issues/4307

However, running in dev and typechecking works. It's just that building the project is currently broken.
