### ISSUE TITLE
it is still 111MB... can it possibly be smaller?

### ISSUE THREAD

**Issue by nonopolarity** [nano-react-app/nano-react-app#12]
the React app is 300MB, and I remember at work, I got an external hard drive that was a PCI card type hard drive and it was 300MB capacity.

The Nano version, after `npm i` is still 111MB...  can it possibly be smaller, like 30MB?  111MB... the 3-D fish tank app in the early 2000s https://serenescreen.com/v2/ was only about 1.6MB.

video demo of it: https://serenescreen.com/v2/video/vid/hhd/18726_Mac_01_analog.mp4?v=2

**Comment by adrianmcli** [comment]
I believe this is an issue of Javascript development in 2020 w/ NPM and its node_modules system. Your production build should be nowhere near that size however. Closing for now.
