### ISSUE TITLE
ENOENT error on yarn start of freshly created app

### ISSUE THREAD

**Issue by bobbwhy** [nano-react-app/nano-react-app#17]
First, I really like this project so thanks for putting it here.

As for my issue.  A project I created a week ago no longer starts.  
I went ahead and did a fresh project as a test and tried starting it.  Same error:

The problem has come up since moved from Mojave to Catalina, so that may be an issue. 
Any ideas?   Help would be very much appreciated.

thank you.
 
Mac Version: 10.15.4
Node: 12.14.1

`Roberts-MBP:oof robertlamarca$ yarn start
yarn run v1.22.4
$ parcel index.html
ℹ️ Server running at http://localhost:1234
@parcel/workers: ENOENT: no such file or directory, rename '.../dev/react/oof/.parcel-cache/bd/7ad76ea639d2b33cf4da80868f9f03.blob.40128.1.0' -> '.../dev/react/oof/.parcel-cache/bd/7ad76ea639d2b33cf4da80868f9f03.blob'
Error: ENOENT: no such file or directory, rename '.../dev/react/oof/.parcel-cache/bd/7ad76ea639d2b33cf4da80868f9f03.blob.40128.1.0' -> '.../dev/react/oof/.parcel-cache/bd/7ad76ea639d2b33cf4da80868f9f03.blob'
    at Object.renameSync (fs.js:643:3)
    at WriteStream.<anonymous> (.../dev/react/oof/node_modules/@parcel/fs/lib/NodeFS.js:74:42)
    at WriteStream.emit (events.js:223:5)
    at emitCloseNT (internal/streams/destroy.js:69:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
⠋ Building index.html...`

**Comment by adrianmcli** [comment]
Did you run `npm install` or `yarn` after creating the app?

**Comment by bobbwhy** [comment]
I ran yarn after creating the app and then yarn start

**Comment by adrianmcli** [comment]
@bobbwhy I am unable to reproduce, it works perfectly fine to me.

1. `npx nano-react-app my-app`
2. `cd my-app`
3. `yarn`
4. `yarn start`

`node`: v12.16.3
`yarn`: v1.22.4

**Comment by bobbwhy** [comment]
Adrian,

thanks for your quick replies.  I guess I will try re-installing a few
items or else re-imaging the drive for Catalina since the upgrade seems to
be causing all sorts of obscure problems elsewhere.

Robert

**Comment by adrianmcli** [comment]
@bobbwhy Try the Parcel repo as well: https://github.com/parcel-bundler/parcel

Nano-React-App is just a basic Parcel app.

**Comment by bobbwhy** [comment]
Thanks Adrian,
I will give that a try.

**Comment by bobbwhy** [comment]
Hey Adrian,
I just posted this to parcel as you suggested.
https://github.com/parcel-bundler/parcel/issues/4645

Also, i created a repo of code that causes that error on my system and
posted it there.
Repo is here in case you want to look.
https://gitlab.com/rlamarca/oof

thanks again ,
Robert

**Comment by bobbwhy** [comment]
just updated to latest.  works great now.  Thanks again for your help and this is an awesome project

**Comment by adrianmcli** [comment]
No problem! Glad you were able to figure it out, thanks for engaging :)
