### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by rmrth** [nano-react-app/nano-react-app#20]
Why dependencies are not installed automatically while project is being created. Are there some reasons for this?

**Comment by Emmet-Allen** [comment]
Because this is a minimal react install. Some of the stuff that comes with the standard `create-react-app` is unnecessary bloat.  Though you can always just install the modules by going into your project directory in the terminal and typing `npm install`.

**Comment by adrianmcli** [comment]
also, I don't think we want to be opinionated on Yarn vs NPM.

**Comment by mgreasly** [comment]
I'm going to close this issue as both of the previous answers explain why we're not installing dependencies automatically.
