### ISSUE TITLE
in IE 9/11 not working

### ISSUE THREAD

**Issue by saswat3115** [nano-react-app/nano-react-app#23]
I see babel is included. but still in IE9/11 its not working

**Comment by saswat3115** [comment]
Any suggestion on this issue ?

**Comment by adrianmcli** [comment]
You should ask in the Parcel Github: https://github.com/parcel-bundler/parcel

**Comment by mgreasly** [comment]
I'm going to close this issue - we're not using Parcel anymore. No idea if we're supporting IE9/11, but they're pretty legacy now. We can re-open if anyone reports an issue with older browser support.
