### ISSUE TITLE
Swapping Parcel to ESbuild?

### ISSUE THREAD

**Issue by rocketteering** [nano-react-app/nano-react-app#24]
I've used nano-react-app a lot and I'm really a fan of it, but more often than not, I'm running into issues with the newest Parcel 2 and I always end-up downgrading it to lower version, which causes even more issues, since it's incompatible with the nano-react-app configurations.

I've thought about creating a fork out of nano-react-app and substituting Parcel with ESBuild https://github.com/evanw/esbuild, to get rid of the problems and speed up the bundling. But before building my own solution, could this be incorporated into nano-react-app?

**Comment by kotx** [comment]
Bump :)
Any update on this?

**Comment by adrianmcli** [comment]
Is esbuild as zero config as parcel?

**Comment by rocketteering** [comment]
It's not, some configuration is definitely required and to my understanding, things like HMR need to implemented by yourself.

**Comment by mgreasly** [comment]
Just to round this off - there's a PR raised to move the project to Vite (https://vitejs.dev/) instead of Parcel for build. Same no-config setup but faster & more modern build tool.
