### ISSUE TITLE
Proxy not working.

### ISSUE THREAD

**Issue by Hexorshift** [nano-react-app/nano-react-app#28]
Trying to proxy while developing a full-stack app doesn't seem to work.

**Comment by adrianmcli** [comment]
what do you mean by proxy?

**Comment by Hexorshift** [comment]
Hey, this will explain what I mean.
https://create-react-app.dev/docs/proxying-api-requests-in-development/

**Comment by mgreasly** [comment]
We've moved nano-react-app to use ViteJS as the build tool now. That does support proxy functionality, but you need to add a config file to set this up, it's documented on the ViteJS website at https://vitejs.dev/config/#server-proxy.
