### ISSUE TITLE
Hot Reloading isn't working on Webstorm

### ISSUE THREAD

**Issue by saimanish1** [nano-react-app/nano-react-app#3]
I've tried it on Webstorm in ubuntu. Webstorm saves automatically without pressing ctrl + s. Generally hot reloading works on ctrl +s on create-react-app but in this case it isn't.

**Comment by adrianmcli** [comment]
Would this have something to do with how Parcel watches file changes? I've said this elsewhere, but this is really just a simple Parcel app. So it might make sense to ask this on the Parcel repo: https://github.com/parcel-bundler/parcel/issues

**Comment by saimanish1** [comment]
Yeah I've gone through their issues page. Seems like many people are facing this problem even on vscode but it works fine for me on vscode.

**Comment by adrianmcli** [comment]
Would be good to link that issue here as well.

**Comment by saimanish1** [comment]
https://github.com/parcel-bundler/parcel/issues/2727

**Comment by yzaroui** [comment]
Maybe disable `safe write` in Webstorm setting. Docs say:

> If this checkbox is selected, a changed file is first saved in a temporary file. If the save operation succeeds, the file being saved is replaced with the saved file. (Technically, the original file is deleted and the temporary file is renamed.)

**Comment by adrianmcli** [comment]
Closing for now.
