### ISSUE TITLE
Just `$ npx create-react-app ___ && rm xyz files`

### ISSUE THREAD

**Issue by corysimmons** [nano-react-app/nano-react-app#5]
Was interested in this until I realized it isn't really create-react-app with the trash stripped from it, but rather a Parcel build and other stuff—which makes it not 1-to-1 with CRA, which could make debugging harder.

**Comment by adrianmcli** [comment]
Yes, that is accurate. I never wanted to re-create CRA and just have less files. The whole idea was to ditch Webpack and use Parcel because of all the functionality it has out of the box. The whole idea of ejecting is a leaky abstraction IMO.

**Comment by corysimmons** [comment]
Yeah ejecting isn't great, but 1-to-1 with CRA just sans all the junk files is a nice idea to minimize confusion when something goes wrong.

Agree to disagree I suppose. 🤷‍♂️(still dying for Dan to add templates to CRA like NextJS has)
