### ISSUE TITLE
high severity vulnerability: serialize-to-js

### ISSUE THREAD

**Issue by mjcampagna** [nano-react-app/nano-react-app#7]
So, this is to do with Parcel's dependencies. However, Parcel has been updated. 

I see nano-react-app hasn't been updated in 6-7 months. Can you please bring things up-to-date?

Or if nano-react-app is no longer being maintained -- which is sad, because it's great -- please let us know so that we can move on.

Thanks!

**Comment by adrianmcli** [comment]
@mjcampagna Sorry I have been busy with other projects recently, but I am happy to keep maintaining this project. Do you think you can put in a PR for updated Parcel? If not, I can work on it but I have no guarantees on deadline as I am only one person.

**Comment by mjcampagna** [comment]
Hi,

Thanks for the reply. Glad to hear you'll be keeping up with nano-react-app. The speed things move these days, any time I see anything more than 4-6 months old, I raise an eyebrow.

I've found my way to nano-react-app-template, and will make a PR. Hopefully solid.

**Comment by mjcampagna** [comment]
And it seems as if the vulnerability that raised this conversation is addressed not in the current, stable version of Parcel 1.12.3, but in the upcoming v2 still tagged as alpha ... cé la vie ...

**Comment by adrianmcli** [comment]
We should probably just move to v2 of Parcel to be honest.

**Comment by adrianmcli** [comment]
I'll approve a PR 2 move to v2 of Parcel if you (or anyone else) wants to put one in.

**Comment by adrianmcli** [comment]
I've moved to parcel v2. This should be gone now.
